name: test for tmate

on:
    workflow_dispatch

jobs:
    testTmate:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: simple bash
              run: echo hello world
            - run: | 
               myVar=2
               echo $myVar